### ISSUE TITLE
[Config Issue] Price: Free

### ISSUE THREAD

**Issue by joex92** [IHasName/CustomHeads#34]
## Issue Description

Can't seem to find how to set the prices for Economy...
here's my `config.yml`
```yaml
# --------------------------------------------------- #
# CustomHeads - Headsconfig                           #
# --------------------------------------------------- #
# mainMenu: Sets the Main Menu when you type /heads   #
# What do I put here? -> Use the ID of an Menu used   #
# in the settings.json File under "menus"             #
# --------------------------------------------------- #
# maxUndoHistory: Limits how many times you           #
# can Undo /heads write - default: 6                  #
# --------------------------------------------------- #
# update-notifications: Get notified when the Plugin  #
# has an Update ready - default: true                 #
# --------------------------------------------------- #
# history: Will act as an Search History and used     #
# Heads from /heads get - default: true               #
#                                                     #
# seeown: Players can see their own History           #
# default: false                                      #
#                                                     #
# historyMode can either be TEMP or FILE              #
# Overflow: default: 18 max: 27                       #
# --------------------------------------------------- #
#                 Economy: Category                   #
# buyable: Defines if Categories can be bought with   #
# Money (only available when Economy is enabled)      #
# keePermissions: When set to true, Categories you    #
# have the Permission for will be unlocked without    #
# having to buy them                                  #
#                  Economy: Heads                     #
# buyable: Defines if Heads can be bought with Money  #
# (only available when Economy is enabled)            #
# permanentBuy: Unlocks the Heads permanently once    #
# bought                                              #
# --------------------------------------------------- #
# update-notifications: Choose if you cant to receive #
# Update Notifications Ingame and or via Console      #
# --------------------------------------------------- #
# disabledCategories: A List of Categories which will #
# be ignored by the Plugin                            #
# --------------------------------------------------- #
# langFile: Used to determine which Language is used. #
# You can use the default Languages as template to    #
# create your own Language Settings.                  #
# --------------------------------------------------- #
# reducedDebug: Will suppress any Debug Info from the #
# Plugin                                              #
#                                                     #
# Feel free to send me your Languages so others can   #
# use it too! (You will also be credited in the       #
# description =])                                     #
# --------------------------------------------------- #

mainMenu: main-menu
maxUndoHistory: 6
history:
  seeown: true
  enabled: true
  overflow: 18
economy:
  enable: true
  category:
    buyable: true
    keepPermissions: true
  heads:
    buyable: true
    permanentBuy: false
  get-command:
    price-per-head: 1000
update-notifications:
  onJoin: true
  console: true
disabledCategories: []
langFile: en_EN
reducedDebug: true

```
in-game I just get `Price: Free` for everything when opening with `/cheads`
How do I set prices for heads and categories?
I even tried to look up at the code and try to find how the plugin sets the prices, but I can't seem to find where it gets the prices...

## Infos
  - Plugin Version: 3.0.3
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2): Purpur version git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)
  - Plugins: 3DItems (1.6.1), AdvancedArmorStands (1.17.3.0), AdvancedRegionMarket (3.3.5), AdvancedTabOverlay (1.2.6), ajStartCommands (2.0.3), AnnouncerPlus (1.2.5), ArmorStandEditor (1.18-pre5-30), AuctionHouse (3.0.2), AutomaticSowing (1), AutoPickup (1.3.5-SNAPSHOT), BetterBackpacks (1.1-BETA), BetterConcrete (1.7.0), BetterGiants (2.7), BetterWaypoints (0.3-BETA), BKCommonLib (1.17.1-v4), BlockLocker (1.10.1), BloodNight (0.10.7), Bookshelf (3.0.6.4), ChangeSlots (2.4.0), Chatty (2.19.4), ChestSort (12.0.6), Chunky (1.2.86), ChunkyBorder (1.0.38), Citizens (2.0.28-SNAPSHOT (build 2359)), CMILib (1.0.4.3), Coins (1.10.8), CoreProtect (20.1), CustomCrafting (1.7.1.3), CustomHeads (3.0.3), CustomTime (2.1.1), DangerousCaves (2.2.14-SNAPSHOT), DeadSouls (1.6), Dimensions (2.0.3), DiscordSRV (1.24.0), DiscordSRV-Staff-Chat (1.4.1), DiscordSRVUtils (1.2.5), DoorsReloaded (1.1.2), EasyUnsafeEnchants (1.2), EconomyShopGUI (4.0.1), Elevator (3.11.5), Enchantssquared (1.6), Endermaning (1.1.4), EpicTrade (1.8.6), Essentials (2.19.0), EssentialsAntiBuild (2.19.0), EssentialsGeoIP (2.19.0), EssentialsSpawn (2.19.0), Evolutions (1.1.9), ExtraContexts (2.0-SNAPSHOT), ExtractableEnchantments (9.0), FastAsyncWorldEdit (1.17-370;857090b), floodgate (2.0-SNAPSHOT), Geyser-Spigot (1.4.3-SNAPSHOT), GriefPrevention (16.17.1-2b69191), GSit ([6.0.4.1]), HolographicDisplays (2.4.9), Images (2.2.3), InfiniteScoreboard (1.1.0), InfiniteVouchers (2.2.2), InteractionVisualizer (1.16.3.14), Jobs (5.0.0.9), Lasso (1.5), LevelledMobs (3.2.4 b557), LocketteX (1.6.9), LuckPerms (5.3.74), Maintenance (3.0.7), Maplands (1.1), mcMMO (2.1.205), MineChess (1.12.1), MobsToEggs (1.5.5_5), MoreArmour (2.0.6), MoreMobHeads (1.15_1.0.24.D1), MoreOres (1.12.3), MPHealthPower (1.5.0), Multiverse-CommandDestination (1.2.2), Multiverse-Core (4.3.1-b861), Multiverse-EssentialsSupport (2.5-b3), Multiverse-Inventories (4.2.2-SNAPSHOT-bUNKNOWN), Multiverse-NetherPortals (4.2.2-SNAPSHOT-b804), Multiverse-Portals (4.2.2-SNAPSHOT-b850), MusicBox (2.0.5), MyCommand (5.7.1), NBTAPI (2.8.0), NexEngine (2.0.7.4), NoteBlockAPI (1.6.2-SNAPSHOT), Oh_the_dungeons_youll_go (15.4), Pl3xMap (1.0.0-BETA-162), PlaceholderAPI (2.10.10), PlasmoVoice (1.0.7), PlotSquared (6.1.4), PlugMan (2.2.5), PlugManGUI (3.1), PortalGun (2.2.2), ProtocolLib (4.7.1-SNAPSHOT-b531), PublicStash (1.3.2), Relics (2.2), ReLoot (1.0), SecurityLog (1.5), Shopkeepers (2.13.3), SignBoard (1.6.10), SkinsRestorer (14.1.6), SpigotDash (0.4.2 BETA), StayPut (1.2.1), StreamingDrops (8.1), Tamablefoxes (2.1.6-SNAPSHOT), TangledMaze (2.0.0), Tweakin (3.8.0), vane-core (1.3.2), vane-enchantments (1.3.2), vane-trifles (1.3.2), Vault (1.7.3-b131), VeinMiner (1.17.9), ViaBackwards (4.0.1), ViaVersion (4.0.1), VoidGen (2.0), VoidSpawn (1.19.5), Wild (2.29-7da6164), WolfyUtilities (1.7.3.0), WorldEditSelectionVisualizer (2.1.0), WorldGuard (7.0.5+3827266), ZombieApocalypse (1.4.3)

**Comment by joex92** [comment]
I can't believe it... All the prices are individually set on the **LANGUAGE** files!? 
I suggest you add a `price` placeholder on the `Economy` config for `category` and `heads`...
should look like this:
```yaml
economy:
  enable: true
  category:
    buyable: true
    keepPermissions: true
    price: 100 # you could use 0 for default price idk
  heads:
    buyable: true
    permanentBuy: false
    price: 100
  get-command:
    price-per-head: 1000
```
but it's so inconvenient for the prices to be on the Language files...
